[package]
name = "kyc_rwa"
version = "1.0.0"
authors = []

[addresses]
kyc_rwa_addr = '_'

[dev-addresses]
kyc_rwa_addr = '0x111'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework"}

[dev-dependencies]